# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 268fcec4efcb62232fa11f38cab2e53f5c6f126111d715f598aea366d61acc59f92ab7b48b5876cf7b5541456ce75a0b19741d57867c2d76e1c39b3e4f67da73

test:
  secret_key_base: a8cac72885774e4a5afc79850659e21b9e38d5d9464429595104be7b0dbf6c85a009b86de1677a1b841aba1d6105116d7cbf6ea48a65380395ad71e19730a078

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
